name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4 # Format correct pour GitHub Actions

      - name: Setup pnpm
        uses: pnpm/action-setup@v2 # Format correct pour l'action pnpm
        with:
          version: 8.6.0 # Spécifiez la version de pnpm ici

      - name: Install, build, and upload your site
        uses: withastro/action@v3 # Format correct pour l'action Astro
        with:
          path: . # Optionnel si le projet est dans la racine
          package-manager: pnpm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Format correct pour le déploiement
